// 页面的 ID，目前设想用于识别当前所在页面
export default {
    THIRD_PARTY_INSURANCE_LIST: Symbol('THIRD_PARTY_INSURANCE_LIST'),
    THIRD_PARTY_INSURANCE_PUBLICATION: Symbol('THIRD_PARTY_INSURANCE_PUBLICATION'),
    THIRD_PARTY_DIRECT_PAYMENT_PROCESS: Symbol('THIRD_PARTY_DIRECT_PAYMENT_PROCESS'),
    THIRD_PARTY_DIRECT_PAYMENT_DETAIL: Symbol('THIRD_PARTY_DIRECT_PAYMENT_DETAIL'),
    THIRD_PARTY_INSURANCE_PURCHASING_PROCESS: Symbol('THIRD_PARTY_INSURANCE_PURCHASING_PROCESS'),
    THIRD_PARTY_INSURANCE_PURCHASING_DETAIL: Symbol('THIRD_PARTY_INSURANCE_PURCHASING_DETAIL'),
    THIRD_PARTY_PERSONAL_CENTER: Symbol('THIRD_PARTY_PERSONAL_CENTER'),
    THIRD_PARTY_INSURANCE_DETAIL: Symbol('THIRD_PARTY_INSURANCE_DETAIL'),
};