// 页面的 ID，目前设想用于识别当前所在页面
export default {
    THIRD_PARTY_INSURANCE_LIST: Symbol('THIRD_PARTY_INSURANCE_LIST'),
    INSURANCE_COMPANY_INSURANCE_PUBLICATION: Symbol('INSURANCE_COMPANY_INSURANCE_PUBLICATION'),
    INSURANCE_COMPANY_DIRECT_PAYMENT_PROCESS: Symbol('INSURANCE_COMPANY_DIRECT_PAYMENT_PROCESS'),
    INSURANCE_COMPANY_DIRECT_PAYMENT_DETAIL: Symbol('INSURANCE_COMPANY_DIRECT_PAYMENT_DETAIL'),
    INSURANCE_COMPANY_INSURANCE_PURCHASING_PROCESS: Symbol('INSURANCE_COMPANY_INSURANCE_PURCHASING_PROCESS'),
    INSURANCE_COMPANY_INSURANCE_PURCHASING_DETAIL: Symbol('INSURANCE_COMPANY_INSURANCE_PURCHASING_DETAIL'),
    INSURANCE_COMPANY_PERSONAL_CENTER: Symbol('INSURANCE_COMPANY_PERSONAL_CENTER'),
    INSURANCE_COMPANY_INSURANCE_DETAIL: Symbol('INSURANCE_COMPANY_INSURANCE_DETAIL'),
};